// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

package com.ihaiu.test;

public final class BookOuterClass {
  private BookOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .BookTag tag = 3;</code>
     */
    boolean hasTag();
    /**
     * <code>optional .BookTag tag = 3;</code>
     */
    com.ihaiu.test.Booktag.BookTag getTag();
    /**
     * <code>optional .BookTag tag = 3;</code>
     */
    com.ihaiu.test.Booktag.BookTagOrBuilder getTagOrBuilder();
  }
  /**
   * Protobuf type {@code google.protobuf.Book}
   */
  public  static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.Book)
      BookOrBuilder {
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              com.ihaiu.test.Booktag.BookTag.Builder subBuilder = null;
              if (tag_ != null) {
                subBuilder = tag_.toBuilder();
              }
              tag_ = input.readMessage(com.ihaiu.test.Booktag.BookTag.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tag_);
                tag_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ihaiu.test.BookOuterClass.internal_static_google_protobuf_Book_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ihaiu.test.BookOuterClass.internal_static_google_protobuf_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ihaiu.test.BookOuterClass.Book.class, com.ihaiu.test.BookOuterClass.Book.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_FIELD_NUMBER = 3;
    private com.ihaiu.test.Booktag.BookTag tag_;
    /**
     * <code>optional .BookTag tag = 3;</code>
     */
    public boolean hasTag() {
      return tag_ != null;
    }
    /**
     * <code>optional .BookTag tag = 3;</code>
     */
    public com.ihaiu.test.Booktag.BookTag getTag() {
      return tag_ == null ? com.ihaiu.test.Booktag.BookTag.getDefaultInstance() : tag_;
    }
    /**
     * <code>optional .BookTag tag = 3;</code>
     */
    public com.ihaiu.test.Booktag.BookTagOrBuilder getTagOrBuilder() {
      return getTag();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (tag_ != null) {
        output.writeMessage(3, getTag());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (tag_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTag());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ihaiu.test.BookOuterClass.Book)) {
        return super.equals(obj);
      }
      com.ihaiu.test.BookOuterClass.Book other = (com.ihaiu.test.BookOuterClass.Book) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (hasTag() == other.hasTag());
      if (hasTag()) {
        result = result && getTag()
            .equals(other.getTag());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasTag()) {
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTag().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ihaiu.test.BookOuterClass.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ihaiu.test.BookOuterClass.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ihaiu.test.BookOuterClass.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.Book)
        com.ihaiu.test.BookOuterClass.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ihaiu.test.BookOuterClass.internal_static_google_protobuf_Book_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ihaiu.test.BookOuterClass.internal_static_google_protobuf_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ihaiu.test.BookOuterClass.Book.class, com.ihaiu.test.BookOuterClass.Book.Builder.class);
      }

      // Construct using com.ihaiu.test.BookOuterClass.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (tagBuilder_ == null) {
          tag_ = null;
        } else {
          tag_ = null;
          tagBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ihaiu.test.BookOuterClass.internal_static_google_protobuf_Book_descriptor;
      }

      public com.ihaiu.test.BookOuterClass.Book getDefaultInstanceForType() {
        return com.ihaiu.test.BookOuterClass.Book.getDefaultInstance();
      }

      public com.ihaiu.test.BookOuterClass.Book build() {
        com.ihaiu.test.BookOuterClass.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ihaiu.test.BookOuterClass.Book buildPartial() {
        com.ihaiu.test.BookOuterClass.Book result = new com.ihaiu.test.BookOuterClass.Book(this);
        result.id_ = id_;
        result.name_ = name_;
        if (tagBuilder_ == null) {
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ihaiu.test.BookOuterClass.Book) {
          return mergeFrom((com.ihaiu.test.BookOuterClass.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ihaiu.test.BookOuterClass.Book other) {
        if (other == com.ihaiu.test.BookOuterClass.Book.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTag()) {
          mergeTag(other.getTag());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ihaiu.test.BookOuterClass.Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ihaiu.test.BookOuterClass.Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.ihaiu.test.Booktag.BookTag tag_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ihaiu.test.Booktag.BookTag, com.ihaiu.test.Booktag.BookTag.Builder, com.ihaiu.test.Booktag.BookTagOrBuilder> tagBuilder_;
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public boolean hasTag() {
        return tagBuilder_ != null || tag_ != null;
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public com.ihaiu.test.Booktag.BookTag getTag() {
        if (tagBuilder_ == null) {
          return tag_ == null ? com.ihaiu.test.Booktag.BookTag.getDefaultInstance() : tag_;
        } else {
          return tagBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public Builder setTag(com.ihaiu.test.Booktag.BookTag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tag_ = value;
          onChanged();
        } else {
          tagBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public Builder setTag(
          com.ihaiu.test.Booktag.BookTag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          tag_ = builderForValue.build();
          onChanged();
        } else {
          tagBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public Builder mergeTag(com.ihaiu.test.Booktag.BookTag value) {
        if (tagBuilder_ == null) {
          if (tag_ != null) {
            tag_ =
              com.ihaiu.test.Booktag.BookTag.newBuilder(tag_).mergeFrom(value).buildPartial();
          } else {
            tag_ = value;
          }
          onChanged();
        } else {
          tagBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = null;
          onChanged();
        } else {
          tag_ = null;
          tagBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public com.ihaiu.test.Booktag.BookTag.Builder getTagBuilder() {
        
        onChanged();
        return getTagFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      public com.ihaiu.test.Booktag.BookTagOrBuilder getTagOrBuilder() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilder();
        } else {
          return tag_ == null ?
              com.ihaiu.test.Booktag.BookTag.getDefaultInstance() : tag_;
        }
      }
      /**
       * <code>optional .BookTag tag = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ihaiu.test.Booktag.BookTag, com.ihaiu.test.Booktag.BookTag.Builder, com.ihaiu.test.Booktag.BookTagOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ihaiu.test.Booktag.BookTag, com.ihaiu.test.Booktag.BookTag.Builder, com.ihaiu.test.Booktag.BookTagOrBuilder>(
                  getTag(),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.Book)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.Book)
    private static final com.ihaiu.test.BookOuterClass.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ihaiu.test.BookOuterClass.Book();
    }

    public static com.ihaiu.test.BookOuterClass.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    public com.ihaiu.test.BookOuterClass.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbook.proto\022\017google.protobuf\032\rbooktag.p" +
      "roto\"7\n\004Book\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\025" +
      "\n\003tag\030\003 \001(\0132\010.BookTagB,\n\016com.ihaiu.testP" +
      "\000\370\001\001\242\002\003GPB\252\002\016com.ihaiu.testb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ihaiu.test.Booktag.getDescriptor(),
        }, assigner);
    internal_static_google_protobuf_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Book_descriptor,
        new java.lang.String[] { "Id", "Name", "Tag", });
    com.ihaiu.test.Booktag.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
